// Code generated by go generate; DO NOT EDIT.

package manifest

const (
	ManifestSchemaURL      = "https://varda-dev.github.io/varda-manifest/manifest.schema.json"
	SupportedSchemaVersion = 2
	ExpectedPack           = "varda"
)
