package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const canonicalSchemaURL = "https://varda-dev.github.io/varda-manifest/manifest.schema.json"

type schemaDoc struct {
	ID         string `json:"$id"`
	Properties struct {
		SchemaVersion struct {
			Const json.Number `json:"const"`
		} `json:"schema_version"`
		Pack struct {
			Const string `json:"const"`
		} `json:"pack"`
	} `json:"properties"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRepoRoot()
	if err != nil {
		return err
	}

	raw, err := fetchSchema(canonicalSchemaURL)
	if err != nil {
		return err
	}

	manifestSchemaURL, supportedSchemaVersion, expectedPack, err := extractContract(raw)
	if err != nil {
		return err
	}

	if err := writeSchemaCopy(root, raw); err != nil {
		return err
	}
	if err := writeContractFile(root, manifestSchemaURL, supportedSchemaVersion, expectedPack); err != nil {
		return err
	}

	return nil
}

func fetchSchema(rawURL string) ([]byte, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(rawURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		return nil, fmt.Errorf("fetch schema: HTTP %d %s\n%s", resp.StatusCode, resp.Status, strings.TrimSpace(string(body)))
	}

	return io.ReadAll(resp.Body)
}

func extractContract(raw []byte) (string, int, string, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()

	var doc schemaDoc
	if err := decoder.Decode(&doc); err != nil {
		return "", 0, "", fmt.Errorf("decode schema: %w", err)
	}

	manifestSchemaURL := strings.TrimSpace(doc.ID)
	if manifestSchemaURL == "" {
		manifestSchemaURL = canonicalSchemaURL
	}

	version, err := doc.Properties.SchemaVersion.Const.Int64()
	if err != nil {
		return "", 0, "", fmt.Errorf("extract schema_version.const: %w", err)
	}
	if version <= 0 {
		return "", 0, "", fmt.Errorf("extract schema_version.const: invalid value %d", version)
	}

	expectedPack := strings.TrimSpace(doc.Properties.Pack.Const)
	if expectedPack == "" {
		return "", 0, "", fmt.Errorf("extract pack.const: empty value")
	}

	return manifestSchemaURL, int(version), expectedPack, nil
}

func writeSchemaCopy(root string, raw []byte) error {
	var pretty bytes.Buffer
	if err := json.Indent(&pretty, raw, "", "  "); err != nil {
		return fmt.Errorf("format schema: %w", err)
	}
	pretty.WriteByte('\n')

	path := filepath.Join(root, "internal", "manifest", "schema", "manifest.schema.json")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, pretty.Bytes(), 0o644)
}

func writeContractFile(root, manifestSchemaURL string, supportedSchemaVersion int, expectedPack string) error {
	source := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package manifest

const (
	ManifestSchemaURL      = %q
	SupportedSchemaVersion = %d
	ExpectedPack           = %q
)
`, manifestSchemaURL, supportedSchemaVersion, expectedPack)

	formatted, err := format.Source([]byte(source))
	if err != nil {
		return fmt.Errorf("format contract: %w", err)
	}

	path := filepath.Join(root, "internal", "manifest", "contract_gen.go")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, formatted, 0o644)
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate repo root containing go.mod")
		}
		dir = parent
	}
}
